services:
    db:
        restart: unless-stopped
        image: postgres:15-alpine
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
        expose:
            - 5432

    web:
        restart: unless-stopped
        build: ./backend
        entrypoint: /code/server_entrypoint.sh
        volumes:
            - ./media:/code/django_core/media
        ports:
            - "9000:8000"
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - DJANGO_ALLOWED_HOSTS=backend.coreproject.moe
        depends_on:
            - db

    # redis:
    #     restart: unless-stopped
    #     image: redis:7.0.5-alpine

    # worker:
    #     restart: unless-stopped
    #     build: ./backend
    #     entrypoint: /code/worker_entrypoint.sh
    #     environment:
    #         - CELERY_BROKER_URL='redis://redis:6379/0'
    #         - CELERY_RESULT_BACKEND='redis://redis:6379/0'
    #         - POSTGRES_NAME=postgres
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=supersecretpassword
    #         - POSTGRES_HOST=db
    #         - POSTGRES_PORT=5432
    #         - DJANGO_ALLOWED_HOSTS=backend.coreproject.moe
    #     depends_on:
    #         - web
    #         - redis

volumes:
    pgdata:
